name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup ZMK Build
        uses: zmkfirmware/zmk-build-action@v1
        with:
          shield: pncateho-custom1
          board: nice_nano_v2
